### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by boblgum** [gbprod/uuid-normalizer#3]
There is no tag with name "denormalizer"
```yaml
services:
    uuid_denormalizer:
        class: GBProd\UuidNormalizer\UuidDenormalizer
        tags:
            - { name: serializer.denormalizer }
```
This should be
```yaml
services:
    uuid_denormalizer:
        class: GBProd\UuidNormalizer\UuidDenormalizer
        tags:
            - { name: serializer.normalizer }
```
